const fakeArtworks = [
  {
    id: 1,
    img: "https://picsum.photos/300?random=1",
    author: "Artist 1",
    title: "Artwork 1",
    year: 2021,
    dimension: "23 * 25",
    description: "une belle photo",
    medium: "water with sand",
  },
  {
    id: 2,
    img: "https://picsum.photos/1200?random=2",
    title: "Artwork 2",
    author: "Artist 1",
    year: 2024,
    dimension: "23 * 25",
    description: "une belle photo",
    medium: "water with sand",
  },
  {
    id: 3,
    img: "https://picsum.photos/780?random=3",
    title: "Artwork 3",
    author: "Artist 2",
    year: 2023,
    dimension: "23 * 25",
    description: "une belle photo",
    medium: "water with sand",
  },
  {
    id: 4,
    img: "https://picsum.photos/300?random=4",
    title: "Artwork 4",
    author: "Artist 1",
    year: 2021,
    dimension: "23 * 25",
    description: "une belle photo",
    medium: "water with sand",
  },
  {
    id: 5,
    img: "https://picsum.photos/1200?random=5",
    title: "Artwork 5",
    author: "Artist 1",
    year: 2024,
    dimension: "23 * 25",
    description: "une belle photo",
    medium: "water with sand",
  },
  {
    id: 6,
    img: "https://picsum.photos/780?random=6",
    title: "Artwork 6",
    author: "Artist 2",
    year: 2023,
    dimension: "23 * 25",
    description: "une belle photo",
    medium: "water with sand",
  },
];

export default fakeArtworks;
